### ISSUE TITLE
Deleting line feed between some block causes an error

### ISSUE THREAD

**Issue by amantoux** [fleather-editor/fleather#119]
## Steps to Reproduce

https://github.com/fleather-editor/fleather/assets/17318211/bf22dc0f-c4ab-400c-85c5-4d96f263c64f

```bash
The following assertion was thrown building TextSelectionHandleOverlay(state: _TextSelectionHandleOverlayState#abda9(ticker inactive)):
No child at position TextPosition(offset: 414, affinity: TextAffinity.downstream)
'package:fleather/src/rendering/editable_box.dart':
Failed assertion: line 245 pos 12: 'targetChild != null'

The relevant error-causing widget was: 
  TextSelectionHandleOverlay TextSelectionHandleOverlay:file:///Users/alanmantoux/Coding/fleather/packages/fleather/lib/src/widgets/text_selection.dart:256:12
When the exception was thrown, this was the stack: 
#2      RenderEditableContainerBox.childAtPosition (package:fleather/src/rendering/editable_box.dart:245:12)
#3      RenderEditor.preferredLineHeight (package:fleather/src/rendering/editor.dart:714:19)
#4      _TextSelectionHandleOverlayState.build (package:fleather/src/widgets/text_selection.dart:458:44)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#13     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#33     _invoke (dart:ui/hooks.dart:142:13)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#35     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by amantoux** [comment]
I think guilty line are 
https://github.com/fleather-editor/fleather/blob/4a8453f52f6b79ba1dbbbaa6c970d4b683ef50ca/packages/fleather/lib/src/widgets/text_selection.dart#L175
and
https://github.com/fleather-editor/fleather/blob/4a8453f52f6b79ba1dbbbaa6c970d4b683ef50ca/packages/fleather/lib/src/widgets/text_selection.dart#L193

**Comment by Amir-P** [comment]
Can we merge the #120 and publish a new release to support Flutter 3.10 and then address the problem of using old elements. WDYT? @amantoux

**Comment by amantoux** [comment]
Sure can't be harmful
