### ISSUE TITLE
Exception thrown when programatically deleting characters.

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#219]
## Steps to Reproduce

1. Type a word such as "Hello" into FleatherField.
2. Use the following to programatically delete the last character. In this case, it would be the "o" in "Hello": 

```
     final TextPosition position = TextPosition(offset: notesModel.controller.selection.baseOffset);
                            print(position.offset);
                            notesModel.controller.document.delete(position.offset-1, 1);
```

3. Exception received. On Screen, after a few seconds, sometimes the character will delete, but the cursor goes right back to the beginning of the word.

## Environment
- MacOS
- Flutter version [e.g. 3.16.4]
- Fleather version [e.g. 1.12.0]

## Logs

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
No child at position TextPosition(offset: 5, affinity: TextAffinity.upstream)
'package:fleather/src/rendering/editable_box.dart':
Failed assertion: line 245 pos 12: 'targetChild != null'

The relevant error-causing widget was: 
  FleatherField-[GlobalKey#7b820] FleatherField:file:(redacted):191:30
When the exception was thrown, this was the stack: 
#2      RenderEditableContainerBox.childAtPosition (package:fleather/src/rendering/editable_box.dart:245:12)
#3      RenderEditor._getOffsetForCaret (package:fleather/src/rendering/editor.dart:314:19)
#4      RenderEditor._updateSelectionExtentsVisibility (package:fleather/src/rendering/editor.dart:290:25)
#5      RenderEditor.paint (package:fleather/src/rendering/editor.dart:632:5)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#9      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:486:12)
#10     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4739:13)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#13     _RenderSingleChildViewport.paint.paintContents (package:fleather/src/widgets/single_child_scroll_view.dart:260:17)
#14     _RenderSingleChildViewport.paint (package:fleather/src/widgets/single_child_scroll_view.dart:274:9)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#16     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:166:11)
#17     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:109:5)
#18     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1156:31)
#19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1166:15)
#20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:593:23)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#26     _invoke (dart:ui/hooks.dart:312:13)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#28     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditor#8dab6 relayoutBoundary=up2
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...  size: Size(620.0, 22.0)
RenderObject: RenderEditor#8dab6 relayoutBoundary=up2
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
  size: Size(620.0, 22.0)
...  child 1: RenderEditableTextLine#bd6f1 relayoutBoundary=up3
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...    size: Size(620.0, 22.0)
...    body: RenderParagraphProxy#65ce2 relayoutBoundary=up4
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...      size: Size(620.0, 22.0)
...      child: RenderParagraph#cd65f relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...        size: Size(620.0, 22.0)
...        textAlign: left
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          inherit: true
...          size: 14.0
...          weight: 400
...          height: 1.6x
====================================================================================================

```

**Comment by Amir-P** [comment]
It's a bad practice to make changes directly to document when using it with the editor. In that case you should interact with the controller instead.

```dart
void removeText(int from, int to) {
  _controller!.replaceText(from, to - from, '');
}

**Comment by nialljawad96** [comment]
@Amir-P I've used the above solution to no avail. For example, with the cursor at the end of the word "hello" -  deleting character 3, using length 1, I get "helo".

The character gets deleted after a few seconds, the cursor goes back to the start of "hello", it crashes and I receive this exception:

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
No child at position TextPosition(offset: 5, affinity: TextAffinity.downstream)
'package:fleather/src/rendering/editable_box.dart':
Failed assertion: line 245 pos 12: 'targetChild != null'

The relevant error-causing widget was: 
  FleatherField FleatherField:file:///Users/nialljawad/StudioProjects/purple/lib/notes/textEditor.dart:190:30
When the exception was thrown, this was the stack: 
#2      RenderEditableContainerBox.childAtPosition (package:fleather/src/rendering/editable_box.dart:245:12)
#3      RenderEditor._getOffsetForCaret (package:fleather/src/rendering/editor.dart:314:19)
#4      RenderEditor._updateSelectionExtentsVisibility (package:fleather/src/rendering/editor.dart:290:25)
#5      RenderEditor.paint (package:fleather/src/rendering/editor.dart:631:5)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#9      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:486:12)
#10     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4739:13)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#13     _RenderSingleChildViewport.paint.paintContents (package:fleather/src/widgets/single_child_scroll_view.dart:260:17)
#14     _RenderSingleChildViewport.paint (package:fleather/src/widgets/single_child_scroll_view.dart:274:9)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#16     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:166:11)
#17     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:109:5)
#18     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1156:31)
#19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1166:15)
#20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:593:23)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#26     _invoke (dart:ui/hooks.dart:312:13)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#28     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditor#3d164 relayoutBoundary=up2
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...  size: Size(620.0, 22.0)
RenderObject: RenderEditor#3d164 relayoutBoundary=up2
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
  size: Size(620.0, 22.0)
...  child 1: RenderEditableTextLine#e8d57 relayoutBoundary=up3
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...    size: Size(620.0, 22.0)
...    body: RenderParagraphProxy#cba5e relayoutBoundary=up4
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...      size: Size(620.0, 22.0)
...      child: RenderParagraph#3a1a7 relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=620.0, 0.0<=h<=Infinity)
...        size: Size(620.0, 22.0)
...        textAlign: left
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          inherit: true
...          size: 14.0
...          weight: 400
...          height: 1.6x
====================================================================================================

```

**Comment by nialljawad96** [comment]
@Amir-P This works perfectly - thanks!
