### ISSUE TITLE
Sometimes receive assertion when pressing arrow keys down, and then pressing enter.

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#227]
## Steps to Reproduce

1. Press arrow keys down in fleather field to go lower in the textfield.
2. Press enter a few times.
3. Receive assertion.

This appears to happen particularly when going past (vertically) a text/embed that is already present, with the arrow down key. 

## Environment
- Mac OS
- Flutter version 3.16.4
- Fleather version 1.13.2

## Logs

```

======== Exception caught by services library ======================================================
The following assertion was thrown during method call TextInputClient.updateEditingStateWithDeltas:
'package:parchment/src/document/node.dart': Failed assertion: line 235 pos 12: 'index == 0 || (index > 0 && index < length)': is not true.

When the exception was thrown, this was the stack: 
#2      ContainerNode.insert (package:parchment/src/document/node.dart:235:12)
#3      ParchmentDocument.compose (package:parchment/src/document.dart:246:15)
#4      ParchmentDocument.insert (package:parchment/src/document.dart:123:5)
#5      ParchmentDocument.replace (package:parchment/src/document.dart:162:15)
#6      FleatherController.replaceText (package:fleather/src/widgets/controller.dart:129:24)
#7      RawEditorStateTextInputClientMixin.updateEditingValueWithDeltas (package:fleather/src/widgets/editor_input_client_mixin.dart:159:25)
#8      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#9      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#10     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:559:55)
#11     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:552:34)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#13     _invoke2 (dart:ui/hooks.dart:344:13)
#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#15     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:722:22)
#18     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [91, {deltas: [{selectionBase: 25, oldText: 














￼







, selectionAffinity: TextAffinity.downstream, deltaEnd: 24, deltaText: 
, deltaStart: 24, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 25, composingBase: -1}]}])
====================================================================================================

```

**Comment by amantoux** [comment]
Thanks for reporting this
We will look into it as soon as possible

**Comment by amantoux** [comment]
I was able to reproduce consistently by hit arrow down and extra time after the cursor reached the end of the text.

I could not reproduce on Windows not web
