### ISSUE TITLE
Sometimes when rebuilding tree, and then selecting text, the following assertion is received.

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#275]
## Steps to Reproduce

1. Rebuild tree in some form, then select text.
2. Assertion received

## Environment
- Mac OS 12.6
- Flutter version 3.16.4
- Fleather version 1.14.1

## Logs

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _RenderTheaterMarker:
A ValueNotifier<bool> was used after being disposed.

Once you have called dispose() on a ValueNotifier<bool>, it can no longer be used.
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/nialljawad/StudioProjects/purple/lib/main.dart:148:14
When the exception was thrown, this was the stack: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:271:27)
#3      _SelectionHandleOverlayState.initState (package:fleather/src/widgets/text_selection.dart:1399:24)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
...     Normal element mounting (35 frames)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#41     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#43     Element.updateChildren (package:flutter/src/widgets/framework.dart:4024:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#49     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#55     _invoke (dart:ui/hooks.dart:312:13)
#56     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#57     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================

```

Appears to be related to this in the text_selection.dart:

```
  @override
  void initState() {
    super.initState();

    _controller = AnimationController(
        duration: SelectionOverlay.fadeDuration, vsync: this);

    _handleVisibilityChanged();
    widget.visibility?.addListener(_handleVisibilityChanged);
  }

  void _handleVisibilityChanged() {
    if (widget.visibility?.value ?? true) {
      _controller.forward();
    } else {
      _controller.reverse();
    }
  }
```

Is there a way to get around this/mitigate against it?

**Comment by Amir-P** [comment]
Hi @nialljawad96 , Sorry for the long delay. I wasn't able to reproduce the issue not on `v1.14.1` nor `v1.14.3` on both Flutter `v3.19.3` and `v3.16.4`. This is the sample code I'm using which rebuilds the page on FAB click. Am I missing something? Can you please provide a reproducible minimal code with exact steps to take?

```dart
import 'package:fleather/fleather.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FleatherApp());
}

class FleatherApp extends StatelessWidget {
  const FleatherApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        title: 'Fleather - rich-text editor for Flutter',
        home: HomePage(),
      );
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final FocusNode _focusNode = FocusNode();
  final _controller = FleatherController(
      document: ParchmentDocument.fromJson([
    {'insert': 'Test text\n'}
  ]));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(elevation: 0, title: Text('Fleather Demo')),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {});
        },
        child: Icon(Icons.add_a_photo),
      ),
      body: Column(
        children: [
          FleatherToolbar.basic(controller: _controller),
          Divider(height: 1, thickness: 1, color: Colors.grey.shade200),
          Expanded(
            child: FleatherEditor(
              controller: _controller,
              focusNode: _focusNode,
              padding: EdgeInsets.only(
                left: 16,
                right: 16,
                bottom: MediaQuery.of(context).padding.bottom,
              ),
              maxContentWidth: 800,
            ),
          ),
        ],
      ),
    );
  }
}
```


https://github.com/fleather-editor/fleather/assets/8766492/85077b33-3673-4147-bcfb-fbb6a70ab65e

**Comment by nialljawad96** [comment]
@Amir-P Thanks Amir. My implementation is a few thousand lines, so may be difficult to reproduce. Given the the fact its occuring the specified area of text_selection.dart, and the error log, have you got any idea what might be causing it given your understanding of the library? If I wrap the code I shared above in try-catch statements, I stop receiving the assertion. Realise it's a bit of a band-aid solution but it does stop my project from crashing. 

```
class _SelectionHandleOverlayState extends State<SelectionHandleOverlay>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  Animation<double> get _opacity => _controller.view;

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(
        duration: SelectionOverlay.fadeDuration, vsync: this);
    try {
      _handleVisibilityChanged();
      widget.visibility?.addListener(_handleVisibilityChanged);
    }
    catch (e){

    }

  }

  void _handleVisibilityChanged() {
    try {
      if (widget.visibility?.value ?? true) {
        _controller.forward();
      } else {
        _controller.reverse();
      }
    }
    catch (e){

    }

  }

  @override
  void didUpdateWidget(SelectionHandleOverlay oldWidget) {
    try {
      super.didUpdateWidget(oldWidget);
      oldWidget.visibility?.removeListener(_handleVisibilityChanged);
      _handleVisibilityChanged();
      widget.visibility?.addListener(_handleVisibilityChanged);
    }
    catch (e){

    }

  }
```

**Comment by Amir-P** [comment]
The error indicates that we are using a disposed notifier in `initState` of `_SelectionHandleOverlayState` and `_SelectionHandleOverlay` is created by calling `showHandles`. Given the fact that after disposing selection overlay we are getting rid of the reference to it, it's impossible that we are calling `showHandles` on a disposed selection overlay. My speculation is that we are disposing selection overlay before its state is created and rendered.

Are you able to consistently reproduce the issue with your code? I may have a possible fix that we can test. @nialljawad96

**Comment by nialljawad96** [comment]
Yes I can consistently produce it. Only thing that stops it crashing is the try-catch statements. 

A few things that I'm doing if it helps: 
1) Using a listener attached to a focus node that is put within FleatherField, and then requesting/unrequesting focus externally to this. 
2) Using overlays that appear depending on whether a certain text is entered.

**Comment by Amir-P** [comment]
Could you test your project with fd51c48? @nialljawad96 

```yaml
fleather:
  git:
    url: https://github.com/fleather-editor/fleather
    ref: fix/disposed_notifier_usage_after_selection_overlay_disposal
    path: packages/fleather
```

**Comment by nialljawad96** [comment]
@Amir-P Thanks Amir. I've been testing this for the past 24 hours. So far, so good. Will let you know if I have any issues!

**Comment by Amir-P** [comment]
Glad it worked. I will add the tests and create the PR later. @nialljawad96

**Comment by Amir-P** [comment]
I just realized what I did was just redundant and couldn't fix the issue you're facing. The dispose method on `SelectionOverlay` already tries to hide the handles but handles are created in post frame callback and sometimes it happens after the `SelectionOverlay` disposed.
https://github.com/fleather-editor/fleather/blob/596b61a711862814bc91cb828886e1bb5f6cc9bc/packages/fleather/lib/src/widgets/text_selection.dart#L308
https://github.com/fleather-editor/fleather/blob/596b61a711862814bc91cb828886e1bb5f6cc9bc/packages/fleather/lib/src/widgets/text_selection.dart#L1204-L1207
https://github.com/fleather-editor/fleather/blob/596b61a711862814bc91cb828886e1bb5f6cc9bc/packages/fleather/lib/src/widgets/text_selection.dart#L1173-L1187
Anyway, I was able to reproduce the issue in tests and a new commit added that should fix it. Could you please test again? @nialljawad96

**Comment by nialljawad96** [comment]
@Amir-P Great thanks! Shall I just use the same branch:

```
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/disposed_notifier_usage_after_selection_overlay_disposal
      path: packages/fleather
```

**Comment by Amir-P** [comment]
Yes, it's been pushed on the same branch. @nialljawad96

**Comment by nialljawad96** [comment]
@Amir-P Awesome will let you know if there are any issues!

**Comment by nialljawad96** [comment]
@Amir-P I've encountered the same issue a few times in the past hour. It happened when I use a TextField above FleatherField, and I am quickly changing focus between the two/highlighting text in the FleatherField. 

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building _RenderTheaterMarker:
A ValueNotifier<bool> was used after being disposed.

Once you have called dispose() on a ValueNotifier<bool>, it can no longer be used.
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/nj/Development/quantum/lib/main.dart:164:14
When the exception was thrown, this was the stack: 
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:271:27)
#3      _SelectionHandleOverlayState.initState (package:fleather/src/widgets/text_selection.dart:1400:24)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
...     Normal element mounting (35 frames)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#41     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#43     Element.updateChildren (package:flutter/src/widgets/framework.dart:4033:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#49     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#55     _invoke (dart:ui/hooks.dart:312:13)
#56     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#57     _drawFrame (dart:ui/hooks.dart:283:31)
============================================================================================
```

**Comment by Amir-P** [comment]
Are you sure you're using the latest version on that branch? `pub` tries to cache and it might be using the previous commit. Please change the dependency to the latest version on `pub.dev` and run `flutter pub get` in your project. Then change it to the git version and run `flutter pub get` again. Please let me know if it fixes the issue so that we can merge the PR and publish a new release. Thanks! @nialljawad96

**Comment by nialljawad96** [comment]
@Amir-P I've used your method to uncache and the error has been fixed. Sorry about that - I will bear that in mind for future testing. Works perfect! Thanks!

**Comment by Amir-P** [comment]
Thanks for checking it! I'm glad we fixed it. @nialljawad96
And regarding the cache problem, I'm sure there is a better way to do it but that's what I normally do. 😀
