### ISSUE TITLE
Frequently loses its own scroll controller

### ISSUE THREAD

**Issue by cyberpwnn** [fleather-editor/fleather#390]
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 157 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:157:12)
#3      RawEditorState._showCaretOnScreen.<anonymous closure> (package:fleather/src/widgets/editor.dart:1607:29)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#10     _invoke (dart:ui/hooks.dart:314:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#12     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 5 frames from class _AssertionError and dart:async)

**Comment by Amir-P** [comment]
Could you please provide a minimal code with reproducible steps? @cyberpwnn

**Comment by cyberpwnn** [comment]
You can cause this with the fleather examples, just on windows specifically.

**Comment by amantoux** [comment]
I'll try to reproduce on windows in a week or so. I don't have a windows computer handy
